# ===========================================
# Application
# ===========================================

spring.application.name=backend

# ===========================================
# Server
# ===========================================

server.port=8080

# ===========================================
# PostgreSQL Database
# ===========================================

spring.datasource.url=${DB_URL}
spring.datasource.username= ${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# ===========================================
# JPA / Hibernate
# ===========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===========================================
# Multipart File Upload
# ===========================================

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Upload folder
file.upload-dir=uploads

# ===========================================
# OpenRouter AI
# ===========================================

openrouter.api.url=https://openrouter.ai/api/v1/chat/completions
openrouter.api.key=${OPENROUTER_API_KEY}

# AI Model
openrouter.model=openai/gpt-4.1-mini

# ===========================================
# Logging (Optional)
# ===========================================

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE